version: "3.8"
networks:
  docker-network:
    driver: bridge
services:
  crypto-data-api:
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    networks:
      - docker-network
    ports:
      - "3001:3001"
    build:
      context: ./crypto-data-api/dist
      target: prod
    volumes:
      - ./crypto-data/dex-guru-proxy-server.py:/crypto-data-api/dex-guru-proxy-server.py
      - ./crypto-data/requirements.txt:/crypto-data-api/requirements.txt
      - ./crypto-data-api/dist:/crypto-data-api
      - ./crypto-data-api/package.json:/crypto-data-api/package.json
      - ./crypto-data-api/crypto-data-1.0.2.tgz:/crypto-data-api/crypto-data-1.0.2.tgz
    command: >
      sh -c "cd /crypto-data-api && pip3 install -r requirements.txt && python3 dex-guru-proxy-server.py & cd /crypto-data-api && npm install && node main.js"
  telegram-client:
    image: python:3.10-alpine
    networks:
      - docker-network
    ports:
      - "2999:2999"
    build:
      context: ./client/
      target: prod
    volumes:
      - ./client/src:/telegram-client
      - ./client/requirements.txt:/telegram-client/requirements.txt
    command: >
      sh -c "cd /telegram-client && pip3 install -r requirements.txt && python3 run_telegram_bot.py"
