version: "3.3"
networks:
  docker-network:
    driver: bridge
services:
  crypto-data-api:
    networks:
      - docker-network
    build:
      dockerfile: crypto-data-api.dev.Dockerfile
      context: ./docker
    ports:
      - "3001:3001"
    volumes:
      - ./crypto-data/install-puppeteer-extra.sh:/crypto-data-api/install-puppeteer-extra.sh
      - ./crypto-data-api/nest-cli.json:/crypto-data-api/nest-cli.json
      - ./crypto-data-api/tsconfig.build.json:/crypto-data-api/tsconfig.build.json
      - ./crypto-data-api/tsconfig.json:/crypto-data-api/tsconfig.json
      - ./crypto-data-api/package.json:/crypto-data-api/package.json
      - ./crypto-data-api/src:/crypto-data-api/src
      - ./crypto-data-api/crypto-data-1.0.5.tgz:/crypto-data-api/crypto-data-1.0.5.tgz
    command: >
      sh -c "cd /crypto-data-api && npm install && npm run build && node dist/main.js"
  telegram-client:
    networks:
      - docker-network
    build:
      dockerfile: telegram-client.dev.Dockerfile
      context: ./docker
    ports:
      - "2999:2999"
    volumes:
      - ./client/src:/telegram-client
      - ./client/requirements.txt:/telegram-client/requirements.txt
    command: >
      sh -c "cd /telegram-client && pip3 install -r requirements.txt && python3 run_telegram_bot.py"
    depends_on:
      - crypto-data-api
